### ISSUE TITLE
Missing information for libotr

### ISSUE THREAD

**Issue by mkody** [mmilata/znc-otr#27]
I don't have an account for the ZNC WIki, but you should add that we need to install the `libotr5-dev` package (eg. here for Debian/Ubuntu-based distros) if we want to compile the module... Or we're getting this:

```
LIBS="-lotr" znc-buildmod otr.cpp
Building "otr.so" for ZNC 1.5.0... otr.cpp:26:26: fatal error: libotr/proto.h: No such file or directory
compilation terminated.
[ !! ] Error while building "otr.so"
make: *** [otr.so] Error 1
```

**Comment by mmilata** [comment]
Thanks for the report! I've edited the page - feel free to reopen the bug if the modification is insufficient: http://wiki.znc.in/Otr#Installing
