### ISSUE TITLE
Cannot run on ZNC 1.6.0 and Ubuntu 14.04

### ISSUE THREAD

**Issue by Cysioland** [mmilata/znc-otr#28]
Error message while loading: `undefined symbol: otrl_context_set_trust`
Compiled from source using znc-buildmod.

**Comment by mmilata** [comment]
@Cysioland Can you try compliling the module by running `make` in its source directory? IIRC znc-buildmod does not link the module with libotr, thus the error.

http://wiki.znc.in/Otr#Installing

**Comment by Cysioland** [comment]
That did the trick,
