### ISSUE TITLE
Unknown command

### ISSUE THREAD

**Issue by Betaman2k** [mmilata/znc-otr#33]
Heya

OS: Debian 9 latest updates ( 64 bit )
ZNC: 1.7 stable
OTR: latest from ur source

If i wanna start a Chat with this command ?OTR?

i get this error

<b>myusername</b> Unknown command
If Unknown command
See Unknown command

if i used this command

/msg *otr info

works fine <*otr> Your fingerprint: xxx xxx xxx xxx

what is broken ?
i hope u can help me
cya
betman

**Comment by mmilata** [comment]
@Betaman2k are you able to start the chat by sending the recipient a private message that says `?OTR?`?

btw the module is currently unmaintained, so there's noone to fix this bad UI:(
